# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.6.1
      - image: circleci/postgres:9.6
      - image: mysql:5.7
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      APP_URL: http://${HOST}:${PORT}
      NODE_ENV: development
      CACHE_VIEWS: false
      APP_KEY: qMxw3wZUeSTlgy6stqyb9JIQIdmeR5iv
      DB_CONNECTION: pg
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD:
      DB_DATABASE: adonis
      LEGACY_DB_CLIENT: mysql
      LEGACY_DB_HOST: 127.0.0.1
      LEGACY_DB_PORT: 3306
      LEGACY_DB_USER: root
      LEGACY_DB_PASSWORD:
      LEGACY_DB_DATABASE: iv120

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Migrate database
      - run: yarn migrate

      # Seed database
      - run: yarn seed

      # run tests!
      - run: yarn test