const exceptions = {
  PENDING_APPLICATION_EXISTS: 'PENDING_APPLICATION_EXISTS',
  APPLICATION_STATUS_ALREADY_SET: 'APPLICATION_STATUS_ALREADY_SET',
  LEGACY_USER_INCOMPLETE: 'LEGACY_USER_INCOMPLETE',
  PARAMETERS_INVALID: 'PARAMETERS_INVALID',
  AVAILABILITY_PARAMETERS_INVALID: 'AVAILABILITY_PARAMETERS_INVALID'
}

module.exports = Object.freeze(exceptions)
